version: 2

sources:
  - name: raw
    database: fatiamh
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date
          - name: orders_id
            description: the id
          - name: pdt_id
            description: the id
          - name: revenue
            description: the revenue
          - name: quantity
            description: the revenue    
        tests:
          - unique:
              column_name: "(orders_id||'-'||pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
         - name: products_id
           description: Primery_key to the table
           tests:
              - unique
              - not_null         
      - name: ship
        identifier: raw_gz_ship
        description: ship item of greenweez
        columns:
          - name: orders_id
            description: Primery_key to the table
            tests:
               - unique
               - not_null
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
                