version: 1

sources:
  - name: raw
    database: fatiamh
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
        identifier: sales
      - name: raw_gz_product
        identifier: product
      - name: raw_gz_ship
        identifier: ship